format_version: v1.0
configName: lcc_rgb565_mxt_ck_cu
folderName: legato_blank_quickstart_ck_cu_wqvga
frameworkPath: C:\microchip\harmony3
processor: PIC32CK2051GC01144
projectName: legato_blank_quickstart_ck_cu_wqvga
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CK-GC_DFP\1.0.121\PIC32CK-GC01\atdf\PIC32CK2051GC01144.atdf
